version: '3'
services:
  flask:
    image: webapp-flask
    build:
      context: ./server
      dockerfile: Dockerfile-flask
    volumes:
      - "./:/__init__"
  nginx:
    image: webapp-nginx
    build:
      context: ./server
      dockerfile: Dockerfile-nginx
    ports:
      - 5000:80
    depends_on:
      - flask
  client:
    container_name: dashboard
    build:
      context: ./client/
      dockerfile: Dockerfile
    volumes:
      - ./client:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      NODE_ENV: development
    ports:
      - 3000:3000
